# ===================== FXBOT CONFIG — 24/7 (APENAS ESTRATÉGIAS, ASSERTIVO) =====================

symbols: ["USDJPY", "EURUSD", "GBPUSD", "AUDUSD", "USDCAD", "EURJPY"]

timeframe_exec: "M5"
timeframe_regime: "H1"
cooldown_minutes: 8
magic: 5120812
log_level: "INFO"
log_every_bar: false

strategy:
  class_path: "strategies.ensemble_router.EnsembleRouter"
  params:
    mode: "best_conf"
    children:
      - class_path: "strategies.vwap_keltner.VWAPKeltner"
        params:
          k_ema_len: 20
          k_atr_len: 10
          k_mult: 1.8
          adx_thr: 18
          rsi_len: 14
          rsi_trig: 50
          near_vwap_by_atr: 0.35
          confirm_ema20: true
          allow_break_close: true
          min_break_atr: 0.12
          min_room_atr: 1.30
          min_bars: 150
          donchian: 16

      - class_path: "strategies.donchian_adx.DonchianADX"
        params:
          donchian: 16
          adx_thr: 18
          ema_fast: 20
          ema_mid: 50
          ema_slow: 200
          allow_close_break: true
          min_break_atr: 0.12
          min_bars: 150

      - class_path: "strategies.breakout_volume.BreakoutVolume"
        params:
          sr_win: 24
          vol_lookback: 20
          vol_mult: 1.8
          adx_thr: 16
          allow_retest: true
          min_bars: 200
          min_break_atr: 0.12
          retest_vol_relax: 0.90

      - class_path: "strategies.scalper_rsi_bb.ScalperRSIBB"
        params:
          rsi_len: 14
          rsi_buy: 22
          rsi_sell: 78
          bb_len: 20
          bb_k: 2.0
          max_adx_h1: 14
          min_bars: 120

broker:
  class_path: "adapters.mt5.MT5Broker"
  params:
    deviation: 30

session:
  hours: 24
  start_hour: 0
  end_hour: 24
  profit_target_pct: 3.0
  loss_limit_pct: 4.0
  continue_after_target: true
  max_concurrent_trades: 2
  allow_pyramiding: false
  max_stack_per_symbol: 1
  min_stack_increase_r: 0.6
  pyramiding_risk_scale: 0.5

risk:
  risk_per_trade_pct: 0.35
  risk_per_trade_pct_after_target: 0.20
  atr_mult_sl: 1.6
  atr_mult_tp: 3.2
  atr_trail_mult: 1.20
  partial_at_1r: 0.50
  partial_r: 1.0
  trail_start_r: 1.35

spread:
  hard_cap_points: 30
  max_atr_ratio: 0.60
  # allow_grace: false   # se for implementar flag opcional

gate:
  min_conf_base: 0.62   # base sem ML
  thr_min: 0.55
  thr_max: 0.75
  spread_rel_k: 0.60
  spread_rel_add: 0.03  # penaliza threshold quando spread_rel > 0.60
  adx_relax_min: 25
  adx_relax_add: -0.02  # relaxa um pouco com ADX muito forte

# ml_model:
#   class_path: "ml.models.SeuModelo"
#   params:
#     threshold: 0.5
#     ...
